
window.WORD_LIST=[
{id:1,en:"agree",ja:"賛成する，意見が一致する，（with~）合う"},
{id:2,en:"oppose",ja:"に反対する"},
{id:3,en:"advise",ja:"忠告する"},
{id:4,en:"tip",ja:"助言，ヒント，チップ，（足や山などの）先，先端"},
{id:5,en:"discuss",ja:"について話し合う，議論する，話題に出す"},
{id:6,en:"blame",ja:"〜に責任があるとする"},
{id:7,en:"argue",ja:"(that S V)〜と主張する，（with~）言い争う"},
{id:8,en:"claim",ja:"(that S V)〜と主張する，〜を要求する，〜を主張する，主張，要求"},
{id:9,en:"complain",ja:"文句を言う，苦情を言う，（of~）訴える"},
{id:10,en:"offer",ja:"〜を申し出る，申し出，値引き"},
{id:11,en:"suggest",ja:"〜を示唆する，〜を提案する"},
{id:12,en:"recommend",ja:"〜を推薦する，勧める"},
{id:13,en:"grateful",ja:"感謝している"},
{id:14,en:"apologize",ja:"(to~)謝る"},
{id:15,en:"excuse",ja:"言い訳，〜を許す，(A from B)BからAを免除する"},
{id:16,en:"celebrate",ja:"〜を祝う，を挙行する，執り行う"},
{id:17,en:"admire",ja:"〜に感心する，称賛する"},
{id:18,en:"impress",ja:"〜に感銘を与える，〜を感心させる"},
{id:19,en:"award",ja:"賞，〜を授与する"},
{id:20,en:"describe",ja:"〜を説明する(言葉)"},
{id:21,en:"explain",ja:"〜を説明する（行動）"},
{id:22,en:"communicate",ja:"(with~)意思の疎通をはかる，〜を伝える"},
{id:23,en:"express",ja:"を表現する，急行"},
{id:24,en:"promise",ja:"約束，約束する"},
{id:25,en:"information",ja:"情報"},
{id:26,en:"technology",ja:"技術"},
{id:27,en:"research",ja:"研究，研究する"},
{id:28,en:"material",ja:"材料，生地，資料，教材，物質的な，重大な"},
{id:29,en:"artificial",ja:"人工的な"},
{id:30,en:"electric",ja:"電気の，電動の"},
{id:31,en:"invent",ja:"〜を発明する，をでっち上げる"},
{id:32,en:"discover",ja:"発見する，(that S V)〜を知る，〜に気がつく，〜に出会う"},
{id:33,en:"develop",ja:"発達する，発達させる，開発する，発展させる，かかる"},
{id:34,en:"skill",ja:"技術，力"},
{id:35,en:"ability",ja:"能力"}
];
